name: slim/deploy

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    container:
      image: node:20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Clone and install SLIM dependencies
        run: |
          git clone --branch "$SLIM_BRANCH" https://github.com/ImagingDataCommons/slim.git
          cd slim
          yarn install --frozen-lockfile
        env:
          SLIM_BRANCH: ${{ vars.SLIM_BRANCH || 'master' }}

      - name: Build slim
        run: |
          cd slim
          wget -O ./firebase.json "${{ vars.SLIM_FIREBASE_JSON_URL }}"
          wget -O ./public/config/test.js "${{ vars.SLIM_CONFIG_JS_URL }}"
          REACT_APP_CONFIG=test PUBLIC_URL=/ yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0.7.1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 5d
          projectId: "${{ vars.FIREBASE_PROJECT_ID }}"
          entryPoint: ./slim
          channelId: live
          # channelId: # 'pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}'
